modLoader="javafml"
loaderVersion="[4,)"
license="GNU GPLv3"

[[mods]]
modId="distrocraft_player"
version="1.0.1"
displayName="Distrocraft Player"
description="""
Contribute your spare resources to a Minecraft server.
"""
authors="Stuf_y"

[[dependencies.distrocraft_player]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.distrocraft_player]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="CLIENT"
