modLoader="javafml"
loaderVersion="[4,)"
license="GNU GPLv3"

[[mods]]
modId="distrocraft_server"
version="1.0.0"
displayName="Distrocraft Server"
description="""
Distrocraft Server Mod — distributes compute tasks to connected player clients.
"""
authors="Stuf_y"

[[dependencies.distrocraft_server]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.distrocraft_server]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="SERVER"
